name: "🔧 Refactor"
description: 리팩토링할 때 사용해주세요
title: "[refactor] :: "
labels: ["refactor"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 📄 설명
      description: 수정할 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
      placeholder: 최대한 세분화해서 적어주세요!
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요!