name: upik

on:
  push:
    paths:
      - "apps/admin/**"
      - "apps/client/**"
  pull_request:
    paths:
      - "apps/admin/**"
      - "apps/client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Debug 현재 위치 확인
        run: |
          echo "pwd: $(pwd)"
          echo "github.workspace: $GITHUB_WORKSPACE"
          ls -al

      - name: Install dependencies 
        run: pnpm install

      - name: Prettier 코드 포맷 검사 
        run: pnpm format

      - name: Build admin app 
        run: pnpm turbo run build --filter=apps/admin --continue

      - name: Build client app 
        run: pnpm turbo run build --filter=apps/client --continue

      - name: 테스트 실행 
        run: pnpm test
