name: upik

on:
  push:
    paths:
      - "apps/admin/**"
      - "apps/client/**"
  pull_request:
    paths:
      - "apps/admin/**"
      - "apps/client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Debug working directory
        run: |
          echo "현재 경로: $(pwd)"
          echo "Github workspace: $GITHUB_WORKSPACE"
          ls -al
          
      - name: Install dependencies 
        run: |
          cd $GITHUB_WORKSPACE
          pnpm install

      - name: Prettier 코드 포맷 검사 
        run: |
          cd $GITHUB_WORKSPACE
          pnpm format
          
      - name: Build admin app 🛠
        run: |
          cd $GITHUB_WORKSPACE
          pnpm turbo run build --filter=apps/admin --continue
          
      - name: Build client app 🛠
        run: |
          cd $GITHUB_WORKSPACE
          pnpm turbo run build --filter=apps/client --continue

      - name: 테스트 실행 
        run: |
          cd $GITHUB_WORKSPACE
          pnpm test
