name: Upik Workflows

on:
  push:
    paths:
      - "apps/admin/**"
      - "apps/client/**"
  pull_request:
    paths:
      - "apps/admin/**"
      - "apps/client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 23 설치
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'pnpm'

      - name: pnpm 설치
        run: npm install -g pnpm

      - name: 의존성 설치
        run: pnpm install

      - name: Prettier 코드 포맷 검사
        run: pnpm prettier --check .

      - name: 테스트 실행
        run: pnpm test