name: upik

on:
  push:
    paths:
      - "apps/admin/**"
      - "apps/client/**"
  pull_request:
    paths:
      - "apps/admin/**"
      - "apps/client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 디버깅 - 디렉토리 구조 확인
        run: |
          echo "현재 위치 확인:"
          pwd
          echo "상위 폴더 구조:"
          ls -al
          echo "upik_realfront 내부 구조:"
          ls -al upik_realfront
          echo "package.json 위치 확인:"
          cat upik_realfront/package.json | grep name

      - name: Install dependencies
        run: pnpm install

      - name: Prettier 코드 포맷 검사
        run: pnpm prettier --check .

      - name: Build admin app
        run: pnpm turbo run build --filter=./apps/admin --continue

      - name: Build client app
        run: pnpm turbo run build --filter=./apps/client --continue

      - name: 테스트 실행
        run: pnpm test
