name: upik

on:
  push:
    paths:
      - "apps/admin/**"
      - "apps/client/**"
  pull_request:
    paths:
      - "apps/admin/**"
      - "apps/client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: upik_realfront

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: 디버그용 디렉토리 구조 확인
        run: |
              pwd tree -L 2

      - name: Install dependencies
        run: pnpm install
        working-directory: upik_realfront

      - name: Prettier 코드 포맷 검사
        run: pnpm prettier --check .
        working-directory: upik_realfront

      - name: Build admin app
        run: pnpm turbo run build --filter=./apps/admin --continue
        working-directory: upik_realfront

      - name: Build client app
        run: pnpm turbo run build --filter=./apps/client --continue
        working-directory: upik_realfront

      - name: 테스트 실행
        run: pnpm test
        working-directory: upik_realfront
